In [1]:
import numpy as np

In [2]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [4]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [5]:
A = np.random.randn(10)

A

array([2.27325803, 0.24286189, 0.60063044, 0.12914911, 0.84240704,
       1.66801863, 0.68241529, 0.24027674, 0.33754878, 0.48306971])

In [6]:
B = np.random.randn(10)

B

array([ 2.23129614, -0.58722815, -0.08730102,  0.05955021, -0.68241509,
       -0.5717396 , -0.35384641, -1.47390069, -0.25728887,  0.59986546])

In [7]:
# Binary Functions
np.add(A,B)

array([ 4.50455417, -0.34436625,  0.51332942,  0.18869932,  0.15999195,
        1.09627902,  0.32856888, -1.23362395,  0.08025991,  1.08293517])

In [8]:
np.maximum(A,B)

array([2.27325803, 0.24286189, 0.60063044, 0.12914911, 0.84240704,
       1.66801863, 0.68241529, 0.24027674, 0.33754878, 0.59986546])

In [9]:
np.minimum(A,B)

array([ 2.23129614, -0.58722815, -0.08730102,  0.05955021, -0.68241509,
       -0.5717396 , -0.35384641, -1.47390069, -0.25728887,  0.48306971])

In [10]:
website = "https://www.google.com/"
import webbrowser
webbrowser.open(website)

True